---
title: "Title"
output: html_document
---
## Getting Started

```{r temp, results="hide", message=FALSE, warning=FALSE}

# Setting Directory and Importing Files

setwd(list.dirs(path = "/Users/jessicalerner/Documents/CT.Mirror/Olympics"))

state.gender <- read.csv(file = "state.gender.csv")

# Loading Libraries

library(readxl)
library(tidyr)
library(stringr)
library(dplyr)
library(ggplot2)
library(splitstackshape)
library(plyr)
library(grid)
library(gridExtra)
library(scales)
```

##Creating Back-to-Back Bar Graph

```{r temp1, results="hide", message=FALSE, warning=FALSE}

state.gender$State <- factor(state.gender$State, 
                             levels = state.gender$State[order(state.gender$Percent.male)])

g.mid<-ggplot(state.gender,aes(x=1,y=State))+geom_text(aes(label=State))+
  geom_segment(aes(x=0.94,xend=0.96,yend=State))+
  geom_segment(aes(x=1.04,xend=1.065,yend=State))+
  ggtitle("")+
  ylab(NULL)+
  scale_x_continuous(expand=c(0,0),limits=c(0.94,1.065))+
  theme(axis.title=element_blank(),
        panel.grid=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.background=element_blank(),
        axis.text.x=element_text(color=NA),
        axis.ticks.x=element_line(color=NA),
        plot.margin = unit(c(1,-1,1,-1), "mm"))

g1 <- ggplot(data = state.gender, aes(x = State, y = Percent.male)) +
  geom_bar(stat = "identity", fill = "light blue") + 
  ggtitle("Percent of male athletes") +
  geom_text(aes(label = scales::percent(Percent.male/100),
                y=Percent.male), size=3, 
            hjust = -.25, color = "black") + 
  theme(axis.title.x = element_blank(), 
        axis.title.y = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.y = element_blank(), 
        plot.margin = unit(c(1,-1,1,0), "mm")) +
  scale_y_continuous(trans = "reverse") + coord_flip()

g2 <- ggplot(data = state.gender, aes(x = State, y = Percent.female)) +xlab(NULL)+
  geom_bar(stat = "identity", fill = "light pink") + 
  ggtitle("Percent of female athletes") +
  geom_text(aes(label = scales::percent(Percent.female/100),
                y=Percent.female), size=3, 
            hjust = 1.1, color = "black") + 
  theme(axis.title.x = element_blank(), axis.title.y = element_blank(), 
        axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        plot.margin = unit(c(1,0,1,-1), "mm")) +
  scale_y_continuous(limits = c(0,90)) +
  coord_flip()

gg1 <- ggplot_gtable(ggplot_build(g1))
gg2 <- ggplot_gtable(ggplot_build(g2))
gg.mid <- ggplot_gtable(ggplot_build(g.mid))

grid.arrange(gg1,gg.mid,gg2,ncol=3,widths=c(4/9,1/9,4/9), 
             top=textGrob("Summer Olympics by state", 
                          gp=gpar(fontsize=15,font=8)),
             bottom=textGrob("Source: United States Olympic Committee", 
                             gp=gpar(fontsize=10,font=8), hjust = 1.3))

```
